### ISSUE TITLE
Using visualizer

### ISSUE THREAD

**Issue by csathob** [wigig-tools/qd-realization#10]
Dear Contributors,
With the current state of the repository, is the visualizer supposed to work? The documentation states that it will be a subsequent deliverable, but the app is already there. Running an example problem the .json output files have been successfully generated. However, the visualizer seems to expect .csv. If I set the output to .csv, the visualizer still doesn't work. Could you please clarify this a little?
Thank you very much in advance!

**Comment by neerajvarshney** [comment]
Hi
We are sorry to inform you that the current visualizer  in Master branch is not working.  but we have a good news that this visualizer has been updated to support new functionalities of our QD software. Hope by the end of this week, We will merge this updated visualizer in the Master branch.  You can drop me an email and I will update you once it is available. 

Best,

Neeraj Varshney
neeraj.varshney@nist.gov

**Comment by neerajvarshney** [comment]
Hi 

Could you please check this branch? 

https://github.com/usnistgov/qd-realization/tree/origin/feature/visualizerJSON

**Comment by csathob** [comment]
Dear Neeraj Varshney,

Thank you very much for your quick and kind answer. I dropped the mail and also checked the suggested branch. The visualizer works with the example, I will play around with it. Thank you one more time!

Best regards,
Botond Csathó

**Comment by tangnist** [comment]
The visualizer now works with the new JSON format.
