### ISSUE TITLE
Massive MIMO PAA

### ISSUE THREAD

**Issue by firyaguna** [wigig-tools/qd-realization#16]
Dear devs

I'm wondering if it's possible to simulate an 8x8 antenna array transmission.
From the example "L-Room-rotation-multiPAAs", I understand that I'd need to write the NodePaa0.dat with the position/orientation of all 64 elements. Is that correct?

Is there any limitation regarding the number of PAAs?
Would you know how the computational cost would increase with the number of PAAs?

Kind regards

**Comment by hanyassasa87** [comment]
Hi,

The implementation supports 8 spatial streams which correspond to 8x8 MIMO configuration, however, as stated in our Wiki page, we never tested this scenario. Of course, increasing the number of PAAs requires more computation.
For the L-Room-rotation-multiPAAs question, please contact the listed authors on the Q-D channel realization software Github page.
